#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        if [ -f "/var/run/radarr/radarr.pid" ]; then
            PID=`cat /var/run/radarr/radarr.pid`
            if kill -0 $PID > /dev/null 2>&1; then
                kill -9 $PID
                rm -Rf /var/run/radarr/radarr.pid
            fi
        fi
		
        if getent passwd radarr >/dev/null 2>&1; then
            userdel -rf radarr
        fi

        if [ -d "/var/run/radarr" ]; then
            rm -Rf /var/run/radarr
        fi

        omv_config_delete "/config/services/radarr"

        if [ -d "/opt/Radarr" ]; then
            rm -Rf /opt/Radarr
        fi
    ;;

        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
